name: Linting

on: pull_request

jobs:
  jest:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm i --frozen-lockfile
      - run: pnpm format:check
